#!/bin/sh
#
# Renders the daemon's configuration from the environment, then hands over.
#
# Configuration comes from environment variables because that is what every
# deployment this ships to speaks: StartOS renders them from its own config
# screen, Umbrel from its app definition, docker-compose from a .env file. The
# TOML file is an implementation detail those users never see, and doc 13 is
# explicit that they must never be asked to edit one.
#
# Nothing here overwrites a file the user wrote. If forktower.toml already exists
# and was not written by this script, it is left alone: someone who has hand-
# edited their configuration has said something, and silently discarding it would
# be the last thing they expect.

set -eu

DATA_DIR="${FORKTOWER_DATA_DIR:-/data}"
CONFIG="${DATA_DIR}/forktower.toml"
SQ_DIR="${DATA_DIR}/sq"

# The marker that says this file is ours to rewrite.
GENERATED_BY="# generated by docker_entrypoint.sh — edit the environment, not this file"

log() { printf '%s\n' "$*" >&2; }

die() {
  log "Forktower cannot start: $*"
  exit 1
}

# ── Rendering without starting ────────────────────────────────────────────────
#
# StartOS 0.4.x supervises each process itself rather than through s6, so it
# needs the configuration written and then wants the entrypoint to get out of the
# way. Same renderer, no handover — one settings path for three deployments,
# which is what stops a configuration bug from being platform-specific.
RENDER_ONLY=0
if [ "${1:-}" = "--render-only" ]; then
  RENDER_ONLY=1
  shift
fi

# ── Asking the image a question ───────────────────────────────────────────────
#
# `docker run <image> --version` and the like have to work without a
# configuration: a health check, or someone establishing what they have, should
# not need a Bitcoin node first. Arguments beginning with a dash go to the
# daemon; anything else is a command to run instead.
if [ "$#" -gt 0 ]; then
  case "$1" in
    -*) exec /usr/local/bin/forktowerd "$@" ;;
     *) exec "$@" ;;
  esac
fi

# ── Required settings ─────────────────────────────────────────────────────────
#
# The address of the user's own Bitcoin node. There is no sensible default: it is
# the one thing only they know, and guessing would produce a daemon watching the
# wrong node and reporting that everything is fine.
if [ -z "${FORKTOWER_SF_RPC_URL:-}" ]; then
  die "set FORKTOWER_SF_RPC_URL to your own Bitcoin node's RPC address,
  for example http://172.17.0.1:8332 — it is the one thing Forktower cannot
  work out for itself."
fi

SQ_MODE="${FORKTOWER_SQ_MODE:-all-in-one}"
case "${SQ_MODE}" in
  all-in-one|external) ;;
  *) die "FORKTOWER_SQ_MODE must be all-in-one or external, not '${SQ_MODE}'" ;;
esac

# ── The second node's address ────────────────────────────────────────────────
if [ "${SQ_MODE}" = "all-in-one" ]; then
  # It runs beside us in this container.
  SQ_RPC_URL="${FORKTOWER_SQ_RPC_URL:-http://127.0.0.1:8432}"
  SQ_ZMQ_BLOCK="${FORKTOWER_SQ_ZMQ_RAWBLOCK:-tcp://127.0.0.1:28432}"
  SQ_ZMQ_TX="${FORKTOWER_SQ_ZMQ_RAWTX:-tcp://127.0.0.1:28433}"
else
  if [ -z "${FORKTOWER_SQ_RPC_URL:-}" ]; then
    die "FORKTOWER_SQ_MODE is external, so set FORKTOWER_SQ_RPC_URL to the
  second Bitcoin node's RPC address."
  fi
  SQ_RPC_URL="${FORKTOWER_SQ_RPC_URL}"
  SQ_ZMQ_BLOCK="${FORKTOWER_SQ_ZMQ_RAWBLOCK:-}"
  SQ_ZMQ_TX="${FORKTOWER_SQ_ZMQ_RAWTX:-}"
fi

mkdir -p "${DATA_DIR}" "${SQ_DIR}"

# ── The second node's configuration ──────────────────────────────────────────
#
# Written here rather than baked into the image because three of its settings are
# load-bearing and easy to get subtly wrong.
write_bitcoin_conf() {
  conf="${SQ_DIR}/bitcoin.conf"

  if [ -f "${conf}" ] && ! head -n1 "${conf}" | grep -qF 'generated by'; then
    log "keeping the bitcoin.conf you wrote at ${conf}"
    return
  fi

  # Peering transport. Everything goes through Tor by default: a second node
  # following only the status-quo chain, from the user's own address, links the
  # two and marks its operator as someone defending Lightning channels across a
  # split — which is targeting information for whoever might breach them.
  # Clearnet is an explicit choice, and the interface says what it costs.
  #
  # **`onlynet=onion` is no longer the default, and that is not a weakening.**
  # `proxy` is what protects the user: every connection is made through Tor, so
  # no peer ever learns their address. `onlynet=onion` additionally refuses to
  # talk to anything but onion peers — which on a cold start is close to
  # crippling, because a node restricted to onion cannot use the DNS seeds and
  # has only the small built-in onion seed list to bootstrap from. Measured on
  # real hardware: four peers held out of a target of eight, two thousand
  # connection attempts churned through in four days, an initial sync that took
  # three days where the same machine's other node took less than one, and then
  # a view that sat permanently DEGRADED for want of peers afterwards.
  #
  # Reaching an ordinary peer through a Tor exit still tells that peer nothing
  # about who is asking. What is given up is that the exit sees Bitcoin P2P
  # traffic — blocks and transactions everyone already has — and what is bought
  # is a node that can actually find the chain it is supposed to be watching.
  #
  # Onion-only remains available for anyone who wants it, because on this
  # question the right answer really does depend on the threat being modelled.
  if [ "${FORKTOWER_SQ_CLEARNET:-false}" = "true" ]; then
    peering="# clearnet peering, enabled explicitly by FORKTOWER_SQ_CLEARNET"
  elif [ "${FORKTOWER_SQ_ONION_ONLY:-false}" = "true" ]; then
    peering="proxy=${FORKTOWER_TOR_PROXY:-127.0.0.1:9050}
# Onion peers only, asked for explicitly. Expect a slow first sync and few
# peers: this node cannot use the DNS seeds and must bootstrap from the built-in
# onion seed list alone.
onlynet=onion"
  else
    peering="proxy=${FORKTOWER_TOR_PROXY:-127.0.0.1:9050}"
  fi

  # ── How this node identifies itself to its peers ───────────────────────────
  #
  # Two purposes, one of them not ours.
  #
  # Ours: two Forktower configurations accidentally pointed at one node produce
  # views that agree by construction, and the user agent is one of the signals
  # that catches it.
  #
  # **Everyone else's: this node should be countable, and discountable.** The
  # ratio of Core to Knots nodes is being watched closely by people on both sides
  # of the question, and a Forktower second node would otherwise be counted as an
  # independent Core node when it is nothing of the kind — it is a *second* node
  # belonging to somebody who already runs one, and it follows the status-quo
  # chain because that is its job rather than because its operator chose a side.
  # Silently inflating one side's numbers would be a small dishonesty performed
  # at scale, so the node says what it is and anyone counting can filter it out.
  #
  # `uacomment` is the mechanism Bitcoin Core provides for this, and the result
  # is `/Satoshi:31.1.0(forktower-0.5.0)/` — the client and its version still
  # read exactly as they would otherwise, which is the point. Patching the binary
  # to mimic the `/Satoshi:.../Knots:.../` shape was considered and rejected: it
  # would mean building Core from source and giving up verification against the
  # published release checksum, which is a real security property traded for a
  # cosmetic one.
  #
  # The cost, stated plainly: a peer we connect to learns that this operator runs
  # Forktower, and therefore that they have Lightning channels they are defending
  # across a split. That is why the connection is made through Tor — the peer
  # learns it about an anonymous node rather than about an address. Anyone who
  # would rather not say at all can set FORKTOWER_SQ_UACOMMENT to an empty value
  # and no comment is written.
  #
  # Sanitised because Bitcoin Core refuses to start on a user agent comment
  # containing `/` or `:`, and a version string arriving from a build system must
  # never be able to stop the node.
  if [ -n "${FORKTOWER_SQ_UACOMMENT+set}" ] && [ -z "${FORKTOWER_SQ_UACOMMENT}" ]; then
    ua_line="# no user agent comment, by explicit request"
  else
    ua_version="$(printf '%s' "${FORKTOWER_VERSION:-dev}" | tr -cd 'A-Za-z0-9.-')"
    # Just `forktower`, with no mention of which chain. Forktower runs exactly
    # one Bitcoin node — the user's own is theirs, and this program only ever
    # reads it — so any node saying `forktower` is this one, and naming the
    # chain added nothing but a two-letter abbreviation a stranger had to look
    # up. It also read like a declaration of allegiance, which it never was.
    ua_line="uacomment=${FORKTOWER_SQ_UACOMMENT:-forktower-${ua_version}}"
  fi

  {
    printf '%s\n' "# generated by docker_entrypoint.sh — edit the environment, not this file"
    cat <<CONF

# The chain the user's own node does not follow. This is ordinary Bitcoin Core
# on a release that predates the new rules, so it follows the status-quo chain
# by construction rather than by configuration.

regtest=0
server=1
listen=1
daemon=0
printtoconsole=1

# Pruned. Forktower never needs arbitrary history older than the point the
# chains separated, and it watches the prune height so it can say something
# before that stops being true.
prune=${FORKTOWER_SQ_PRUNE_MB:-10000}

# No wallet and no address index: this node holds nothing and answers about
# blocks. Its memory pool is kept, because an unconfirmed sighting is what buys
# the user time.
disablewallet=1
blocksonly=${FORKTOWER_SQ_BLOCKSONLY:-0}

# Cache for the UTXO set while catching up. The default is 450 MB, and the
# machines this runs on generally have far more to spare than that — a bigger
# cache means fewer flushes to disk, which is most of what makes a first sync
# slow. Lowered automatically by Core once the chain is caught up, so this is a
# cost paid during the sync and largely returned afterwards.
dbcache=${FORKTOWER_SQ_DBCACHE_MB:-2000}

# Ports of its own. Two Bitcoin nodes on one machine both wanting 8333 is a
# support question nobody should have to ask.
port=${FORKTOWER_SQ_P2P_PORT:-8433}
rpcport=${FORKTOWER_SQ_RPC_PORT:-8432}
rpcbind=127.0.0.1
rpcallowip=127.0.0.1/32
rpcuser=forktower
rpcpassword=${FORKTOWER_SQ_RPC_PASSWORD}

zmqpubrawblock=tcp://127.0.0.1:${FORKTOWER_SQ_ZMQ_BLOCK_PORT:-28432}
zmqpubrawtx=tcp://127.0.0.1:${FORKTOWER_SQ_ZMQ_TX_PORT:-28433}

${ua_line}

${peering}
CONF

    # Anchor peers, so the node has somewhere to start looking for peers that
    # serve the chain it wants. `addnode`, never `connect`: `connect` would
    # restrict it to exactly these and switch off peer discovery, turning the
    # measure meant to prevent an eclipse into a single point of one.
    #
    # The daemon's own copy first, if it has verified one, and the shipped list
    # otherwise. Only `peer:` lines are read — the file also carries the format
    # and version directives that make a replacement checkable, and feeding
    # those to Bitcoin Core as addresses would be a confusing way to fail.
    anchors=/usr/share/forktower/sq-anchors.txt
    [ -f "${DATA_DIR}/anchors/active.txt" ] && anchors="${DATA_DIR}/anchors/active.txt"
    if [ -f "${anchors}" ]; then
      printf '\n# Anchor peers from %s. addnode, never connect: connect would\n' "${anchors}"
      printf '# switch off peer discovery and make these the only view of the chain.\n'
      sed -nE 's/^[[:space:]]*peer:[[:space:]]*(.+)$/addnode=\1/p' "${anchors}"
    fi

    if [ -n "${FORKTOWER_SQ_EXTRA_PEERS:-}" ]; then
      printf '\n# Extra peers from FORKTOWER_SQ_EXTRA_PEERS.\n'
      printf '%s' "${FORKTOWER_SQ_EXTRA_PEERS}" | tr ',' '\n' \
        | while IFS= read -r peer; do
            [ -n "${peer}" ] && printf 'addnode=%s\n' "${peer}"
          done
    fi
  } > "${conf}"

  chmod 600 "${conf}"
  log "wrote ${conf}"
}

# ── Forktower's own configuration ────────────────────────────────────────────
write_forktower_conf() {
  if [ -f "${CONFIG}" ] && ! head -n1 "${CONFIG}" | grep -qF 'generated by'; then
    log "keeping the forktower.toml you wrote at ${CONFIG}"
    return
  fi

  {
    printf '%s\n\n' "${GENERATED_BY}"

    printf '[sf]\n'
    printf 'rpc_url = "%s"\n' "${FORKTOWER_SF_RPC_URL}"
    [ -n "${FORKTOWER_SF_RPC_COOKIE_PATH:-}" ] && \
      printf 'rpc_cookie_path = "%s"\n' "${FORKTOWER_SF_RPC_COOKIE_PATH}"
    [ -n "${FORKTOWER_SF_RPC_USER:-}" ] && printf 'rpc_user = "%s"\n' "${FORKTOWER_SF_RPC_USER}"
    [ -n "${FORKTOWER_SF_RPC_PASSWORD:-}" ] && \
      printf 'rpc_pass = "%s"\n' "${FORKTOWER_SF_RPC_PASSWORD}"
    [ -n "${FORKTOWER_SF_ZMQ_RAWBLOCK:-}" ] && \
      printf 'zmq_rawblock = "%s"\n' "${FORKTOWER_SF_ZMQ_RAWBLOCK}"
    [ -n "${FORKTOWER_SF_ZMQ_RAWTX:-}" ] && \
      printf 'zmq_rawtx = "%s"\n' "${FORKTOWER_SF_ZMQ_RAWTX}"

    printf '\n[sq.bitcoind]\n'
    printf 'rpc_url = "%s"\n' "${SQ_RPC_URL}"
    if [ "${SQ_MODE}" = "all-in-one" ]; then
      printf 'rpc_user = "forktower"\n'
      printf 'rpc_pass = "%s"\n' "${FORKTOWER_SQ_RPC_PASSWORD}"
    else
      [ -n "${FORKTOWER_SQ_RPC_COOKIE_PATH:-}" ] && \
        printf 'rpc_cookie_path = "%s"\n' "${FORKTOWER_SQ_RPC_COOKIE_PATH}"
      [ -n "${FORKTOWER_SQ_RPC_USER:-}" ] && \
        printf 'rpc_user = "%s"\n' "${FORKTOWER_SQ_RPC_USER}"
      [ -n "${FORKTOWER_SQ_RPC_PASSWORD:-}" ] && \
        printf 'rpc_pass = "%s"\n' "${FORKTOWER_SQ_RPC_PASSWORD}"
    fi
    [ -n "${SQ_ZMQ_BLOCK}" ] && printf 'zmq_rawblock = "%s"\n' "${SQ_ZMQ_BLOCK}"
    [ -n "${SQ_ZMQ_TX}" ] && printf 'zmq_rawtx = "%s"\n' "${SQ_ZMQ_TX}"

    if [ -n "${FORKTOWER_FORK_NAME:-}" ]; then
      printf '\n[fork]\n'
      printf 'name = "%s"\n' "${FORKTOWER_FORK_NAME}"
      # Left unset unless the operator insists. The daemon reads it from their
      # own node instead, where it cannot go stale — and a stale value here is
      # more dangerous than a missing one, because it bounds how far their chain
      # is treated as already verified.
      [ -n "${FORKTOWER_FORK_DIVERGENCE_HEIGHT:-}" ] && \
        printf 'divergence_height = %s\n' "${FORKTOWER_FORK_DIVERGENCE_HEIGHT}"
    fi

    printf '\n[ui]\n'
    printf 'listen = "%s"\n' "${FORKTOWER_UI_LISTEN:-0.0.0.0:8330}"
    printf 'auth = "%s"\n' "${FORKTOWER_UI_AUTH:-platform}"
    # A container has to bind every address to be reachable at all, and what
    # decides its exposure is the port publishing outside — which the daemon
    # cannot see. Saying so here is what lets it serve without a password; the
    # published port is what actually restricts it, and the reference compose
    # file publishes to this machine only.
    if [ "${FORKTOWER_UI_AUTH:-platform}" = "none" ]; then
      printf 'access_restricted_externally = true\n'
    fi
    [ -n "${FORKTOWER_UI_PASSWORD_HASH:-}" ] && \
      printf 'password_hash = "%s"\n' "${FORKTOWER_UI_PASSWORD_HASH}"

    # ── The Lightning node, if there is one ────────────────────────────────
    #
    # Optional, and honestly so: Forktower watches both chains with no Lightning
    # node at all. What a node adds is the ability to say *which of your
    # channels* a split would expose, which is the difference between knowing a
    # split happened and knowing what it means for you.
    #
    # Credentials are given as paths, never as the credential itself. And the
    # credential to give is the read-only one the node already wrote for itself:
    # nothing here needs, or will accept the responsibility of holding, anything
    # that can move money.
    if [ -n "${FORKTOWER_LND_REST_URL:-}" ]; then
      printf '\n[[ln.lnd]]\n'
      printf 'rest_addr = "%s"\n' "${FORKTOWER_LND_REST_URL}"
      [ -n "${FORKTOWER_LND_TLS_PATH:-}" ] && \
        printf 'tls_cert_path = "%s"\n' "${FORKTOWER_LND_TLS_PATH}"
      [ -n "${FORKTOWER_LND_MACAROON_PATH:-}" ] && \
        printf 'macaroon_path = "%s"\n' "${FORKTOWER_LND_MACAROON_PATH}"
    fi
    if [ -n "${FORKTOWER_CLN_REST_URL:-}" ]; then
      printf '\n[[ln.cln]]\n'
      printf 'rest_addr = "%s"\n' "${FORKTOWER_CLN_REST_URL}"
      [ -n "${FORKTOWER_CLN_RUNE_PATH:-}" ] && \
        printf 'rune_path = "%s"\n' "${FORKTOWER_CLN_RUNE_PATH}"
      [ -n "${FORKTOWER_CLN_TLS_PATH:-}" ] && \
        printf 'tls_cert_path = "%s"\n' "${FORKTOWER_CLN_TLS_PATH}"
    fi

    printf '\n[store]\n'
    printf 'path = "%s/forktower.db"\n' "${DATA_DIR}"

    printf '\n[log]\n'
    printf 'level = "%s"\n' "${FORKTOWER_LOG_LEVEL:-info}"

    # StartOS raises the alerts itself, by reading this daemon's API: an app
    # container has no path to the notification system, so the daemon cannot
    # push to it and the packaging polls instead. Saying so here is what stops
    # the dashboard telling a StartOS user it has no way to reach them.
    #
    # **Umbrel is deliberately not in this list.** It exposes nothing
    # notification-shaped to an app, so there is no wrapper to poll from and no
    # notification centre to raise anything in. Claiming otherwise would silence
    # the readiness item that exists to tell an Umbrel user to set up ntfy, a
    # webhook or email — and an alarm nobody can hear, reported as working, is
    # worse than no alarm at all.
    case "${FORKTOWER_PLATFORM:-}" in
      startos)
        printf '\n[alerts]\n'
        printf 'platform_notifications = true\n'
        ;;
    esac

    # Notification channels, if any were configured. Anywhere else, a deployment
    # with none will say plainly that it has no way to reach its user — which is
    # true, and better than silence.
    if [ -n "${FORKTOWER_WEBHOOK_URL:-}" ]; then
      printf '\n[[alerts.transport]]\n'
      printf 'name = "webhook"\ntype = "webhook"\nmin_tier = "%s"\n' \
        "${FORKTOWER_WEBHOOK_MIN_TIER:-warning}"
      printf 'url = "%s"\n' "${FORKTOWER_WEBHOOK_URL}"
    fi
    if [ -n "${FORKTOWER_NTFY_URL:-}" ]; then
      printf '\n[[alerts.transport]]\n'
      printf 'name = "ntfy"\ntype = "ntfy"\nmin_tier = "%s"\n' \
        "${FORKTOWER_NTFY_MIN_TIER:-warning}"
      printf 'url = "%s"\n' "${FORKTOWER_NTFY_URL}"
      [ -n "${FORKTOWER_NTFY_TOKEN:-}" ] && \
        printf 'token = "%s"\n' "${FORKTOWER_NTFY_TOKEN}"
    fi
  } > "${CONFIG}"

  # It holds credentials.
  chmod 600 "${CONFIG}"
  log "wrote ${CONFIG}"
}

# A password for the second node's RPC, generated once and kept. Nobody types it
# and nobody should have to: it authenticates one process to another inside the
# same container.
ensure_sq_password() {
  secret="${SQ_DIR}/rpc-password"
  if [ -z "${FORKTOWER_SQ_RPC_PASSWORD:-}" ]; then
    if [ ! -f "${secret}" ]; then
      head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n' > "${secret}"
      chmod 600 "${secret}"
    fi
    FORKTOWER_SQ_RPC_PASSWORD="$(cat "${secret}")"
    export FORKTOWER_SQ_RPC_PASSWORD
  fi
}

ensure_sq_password
if [ "${SQ_MODE}" = "all-in-one" ]; then
  write_bitcoin_conf
fi
write_forktower_conf

chown -R forktower:forktower "${DATA_DIR}" 2>/dev/null || true

if [ "${RENDER_ONLY}" = "1" ]; then
  log "Forktower configuration written (platform ${FORKTOWER_PLATFORM:-unspecified}, ${SQ_MODE})"
  exit 0
fi

log "Forktower starting (platform ${FORKTOWER_PLATFORM:-unspecified}, ${SQ_MODE})"

case "${SQ_MODE}" in
  all-in-one)
    # s6 supervises both processes. It is PID 1 from here.
    exec /init
    ;;
  external)
    # The second node is somebody else's service, so there is nothing to
    # supervise and the daemon can be PID 1 itself — which means it receives the
    # stop signal directly rather than through a layer that might not pass it on.
    #
    # By its full path: s6's tools are only on PATH once s6 is running, and here
    # it is not. Nothing in this container needs root, and a process holding
    # privileges it does not use is a process whose bugs are worth more to
    # somebody.
    exec /command/s6-setuidgid forktower /usr/local/bin/forktowerd --config "${CONFIG}"
    ;;
esac
