#!/bin/sh
#
# Renders the daemon's configuration from the environment, then hands over.
#
# Configuration comes from environment variables because that is what every
# deployment this ships to speaks: StartOS renders them from its own config
# screen, Umbrel from its app definition, docker-compose from a .env file. The
# TOML file is an implementation detail those users never see, and doc 13 is
# explicit that they must never be asked to edit one.
#
# Nothing here overwrites a file the user wrote. If forktower.toml already exists
# and was not written by this script, it is left alone: someone who has hand-
# edited their configuration has said something, and silently discarding it would
# be the last thing they expect.

set -eu

DATA_DIR="${FORKTOWER_DATA_DIR:-/data}"
CONFIG="${DATA_DIR}/forktower.toml"
SQ_DIR="${DATA_DIR}/sq"

# The marker that says this file is ours to rewrite.
GENERATED_BY="# generated by docker_entrypoint.sh — edit the environment, not this file"

log() { printf '%s\n' "$*" >&2; }

die() {
  log "Forktower cannot start: $*"
  exit 1
}

# ── Asking the image a question ───────────────────────────────────────────────
#
# `docker run <image> --version` and the like have to work without a
# configuration: a health check, or someone establishing what they have, should
# not need a Bitcoin node first. Arguments beginning with a dash go to the
# daemon; anything else is a command to run instead.
if [ "$#" -gt 0 ]; then
  case "$1" in
    -*) exec /usr/local/bin/forktowerd "$@" ;;
     *) exec "$@" ;;
  esac
fi

# ── Required settings ─────────────────────────────────────────────────────────
#
# The address of the user's own Bitcoin node. There is no sensible default: it is
# the one thing only they know, and guessing would produce a daemon watching the
# wrong node and reporting that everything is fine.
if [ -z "${FORKTOWER_SF_RPC_URL:-}" ]; then
  die "set FORKTOWER_SF_RPC_URL to your own Bitcoin node's RPC address,
  for example http://172.17.0.1:8332 — it is the one thing Forktower cannot
  work out for itself."
fi

SQ_MODE="${FORKTOWER_SQ_MODE:-all-in-one}"
case "${SQ_MODE}" in
  all-in-one|external) ;;
  *) die "FORKTOWER_SQ_MODE must be all-in-one or external, not '${SQ_MODE}'" ;;
esac

# ── The second node's address ────────────────────────────────────────────────
if [ "${SQ_MODE}" = "all-in-one" ]; then
  # It runs beside us in this container.
  SQ_RPC_URL="${FORKTOWER_SQ_RPC_URL:-http://127.0.0.1:8432}"
  SQ_ZMQ_BLOCK="${FORKTOWER_SQ_ZMQ_RAWBLOCK:-tcp://127.0.0.1:28432}"
  SQ_ZMQ_TX="${FORKTOWER_SQ_ZMQ_RAWTX:-tcp://127.0.0.1:28433}"
else
  if [ -z "${FORKTOWER_SQ_RPC_URL:-}" ]; then
    die "FORKTOWER_SQ_MODE is external, so set FORKTOWER_SQ_RPC_URL to the
  second Bitcoin node's RPC address."
  fi
  SQ_RPC_URL="${FORKTOWER_SQ_RPC_URL}"
  SQ_ZMQ_BLOCK="${FORKTOWER_SQ_ZMQ_RAWBLOCK:-}"
  SQ_ZMQ_TX="${FORKTOWER_SQ_ZMQ_RAWTX:-}"
fi

mkdir -p "${DATA_DIR}" "${SQ_DIR}"

# ── The second node's configuration ──────────────────────────────────────────
#
# Written here rather than baked into the image because three of its settings are
# load-bearing and easy to get subtly wrong.
write_bitcoin_conf() {
  conf="${SQ_DIR}/bitcoin.conf"

  if [ -f "${conf}" ] && ! head -n1 "${conf}" | grep -qF 'generated by'; then
    log "keeping the bitcoin.conf you wrote at ${conf}"
    return
  fi

  # Peering transport. Tor by default: a second node following only the
  # status-quo chain, from the user's own address, links the two and marks its
  # operator as someone defending Lightning channels across a split — which is
  # targeting information for whoever might breach them. Clearnet is an explicit
  # choice, and the interface says what it costs.
  if [ "${FORKTOWER_SQ_CLEARNET:-false}" = "true" ]; then
    peering="# clearnet peering, enabled explicitly by FORKTOWER_SQ_CLEARNET"
  else
    peering="proxy=${FORKTOWER_TOR_PROXY:-127.0.0.1:9050}
onlynet=onion"
  fi

  {
    printf '%s\n' "# generated by docker_entrypoint.sh — edit the environment, not this file"
    cat <<CONF

# The chain the user's own node does not follow. This is ordinary Bitcoin Core
# on a release that predates the new rules, so it follows the status-quo chain
# by construction rather than by configuration.

regtest=0
server=1
listen=1
daemon=0
printtoconsole=1

# Pruned. Forktower never needs arbitrary history older than the point the
# chains separated, and it watches the prune height so it can say something
# before that stops being true.
prune=${FORKTOWER_SQ_PRUNE_MB:-10000}

# No wallet and no address index: this node holds nothing and answers about
# blocks. Its memory pool is kept, because an unconfirmed sighting is what buys
# the user time.
disablewallet=1
blocksonly=${FORKTOWER_SQ_BLOCKSONLY:-0}

# Ports of its own. Two Bitcoin nodes on one machine both wanting 8333 is a
# support question nobody should have to ask.
port=${FORKTOWER_SQ_P2P_PORT:-8433}
rpcport=${FORKTOWER_SQ_RPC_PORT:-8432}
rpcbind=127.0.0.1
rpcallowip=127.0.0.1/32
rpcuser=forktower
rpcpassword=${FORKTOWER_SQ_RPC_PASSWORD}

zmqpubrawblock=tcp://127.0.0.1:${FORKTOWER_SQ_ZMQ_BLOCK_PORT:-28432}
zmqpubrawtx=tcp://127.0.0.1:${FORKTOWER_SQ_ZMQ_TX_PORT:-28433}

# How this node identifies itself to its peers, and — more usefully — to
# Forktower. Two configurations accidentally pointed at one node produce views
# that agree by construction, and this is one of the signals that catches it.
uacomment=${FORKTOWER_SQ_UACOMMENT:-forktower-sq}

${peering}
CONF

    # Anchor peers, so the node has somewhere to start looking for peers that
    # serve the chain it wants. `addnode`, never `connect`: `connect` would
    # restrict it to exactly these and switch off peer discovery, turning the
    # measure meant to prevent an eclipse into a single point of one.
    if [ -f /usr/share/forktower/sq-anchors.txt ]; then
      printf '\n# Anchor peers. addnode, never connect: connect would switch off peer\n'
      printf '# discovery and make these the only view of the chain.\n'
      grep -vE '^\s*(#|$)' /usr/share/forktower/sq-anchors.txt \
        | while IFS= read -r peer; do printf 'addnode=%s\n' "${peer}"; done
    fi

    if [ -n "${FORKTOWER_SQ_EXTRA_PEERS:-}" ]; then
      printf '\n# Extra peers from FORKTOWER_SQ_EXTRA_PEERS.\n'
      printf '%s' "${FORKTOWER_SQ_EXTRA_PEERS}" | tr ',' '\n' \
        | while IFS= read -r peer; do
            [ -n "${peer}" ] && printf 'addnode=%s\n' "${peer}"
          done
    fi
  } > "${conf}"

  chmod 600 "${conf}"
  log "wrote ${conf}"
}

# ── Forktower's own configuration ────────────────────────────────────────────
write_forktower_conf() {
  if [ -f "${CONFIG}" ] && ! head -n1 "${CONFIG}" | grep -qF 'generated by'; then
    log "keeping the forktower.toml you wrote at ${CONFIG}"
    return
  fi

  {
    printf '%s\n\n' "${GENERATED_BY}"

    printf '[sf]\n'
    printf 'rpc_url = "%s"\n' "${FORKTOWER_SF_RPC_URL}"
    [ -n "${FORKTOWER_SF_RPC_COOKIE_PATH:-}" ] && \
      printf 'rpc_cookie_path = "%s"\n' "${FORKTOWER_SF_RPC_COOKIE_PATH}"
    [ -n "${FORKTOWER_SF_RPC_USER:-}" ] && printf 'rpc_user = "%s"\n' "${FORKTOWER_SF_RPC_USER}"
    [ -n "${FORKTOWER_SF_RPC_PASSWORD:-}" ] && \
      printf 'rpc_pass = "%s"\n' "${FORKTOWER_SF_RPC_PASSWORD}"
    [ -n "${FORKTOWER_SF_ZMQ_RAWBLOCK:-}" ] && \
      printf 'zmq_rawblock = "%s"\n' "${FORKTOWER_SF_ZMQ_RAWBLOCK}"
    [ -n "${FORKTOWER_SF_ZMQ_RAWTX:-}" ] && \
      printf 'zmq_rawtx = "%s"\n' "${FORKTOWER_SF_ZMQ_RAWTX}"

    printf '\n[sq.bitcoind]\n'
    printf 'rpc_url = "%s"\n' "${SQ_RPC_URL}"
    if [ "${SQ_MODE}" = "all-in-one" ]; then
      printf 'rpc_user = "forktower"\n'
      printf 'rpc_pass = "%s"\n' "${FORKTOWER_SQ_RPC_PASSWORD}"
    else
      [ -n "${FORKTOWER_SQ_RPC_COOKIE_PATH:-}" ] && \
        printf 'rpc_cookie_path = "%s"\n' "${FORKTOWER_SQ_RPC_COOKIE_PATH}"
      [ -n "${FORKTOWER_SQ_RPC_USER:-}" ] && \
        printf 'rpc_user = "%s"\n' "${FORKTOWER_SQ_RPC_USER}"
      [ -n "${FORKTOWER_SQ_RPC_PASSWORD:-}" ] && \
        printf 'rpc_pass = "%s"\n' "${FORKTOWER_SQ_RPC_PASSWORD}"
    fi
    [ -n "${SQ_ZMQ_BLOCK}" ] && printf 'zmq_rawblock = "%s"\n' "${SQ_ZMQ_BLOCK}"
    [ -n "${SQ_ZMQ_TX}" ] && printf 'zmq_rawtx = "%s"\n' "${SQ_ZMQ_TX}"

    if [ -n "${FORKTOWER_FORK_NAME:-}" ]; then
      printf '\n[fork]\n'
      printf 'name = "%s"\n' "${FORKTOWER_FORK_NAME}"
      # Left unset unless the operator insists. The daemon reads it from their
      # own node instead, where it cannot go stale — and a stale value here is
      # more dangerous than a missing one, because it bounds how far their chain
      # is treated as already verified.
      [ -n "${FORKTOWER_FORK_DIVERGENCE_HEIGHT:-}" ] && \
        printf 'divergence_height = %s\n' "${FORKTOWER_FORK_DIVERGENCE_HEIGHT}"
    fi

    printf '\n[ui]\n'
    printf 'listen = "%s"\n' "${FORKTOWER_UI_LISTEN:-0.0.0.0:8330}"
    printf 'auth = "%s"\n' "${FORKTOWER_UI_AUTH:-platform}"
    # A container has to bind every address to be reachable at all, and what
    # decides its exposure is the port publishing outside — which the daemon
    # cannot see. Saying so here is what lets it serve without a password; the
    # published port is what actually restricts it, and the reference compose
    # file publishes to this machine only.
    if [ "${FORKTOWER_UI_AUTH:-platform}" = "none" ]; then
      printf 'access_restricted_externally = true\n'
    fi
    [ -n "${FORKTOWER_UI_PASSWORD_HASH:-}" ] && \
      printf 'password_hash = "%s"\n' "${FORKTOWER_UI_PASSWORD_HASH}"

    printf '\n[store]\n'
    printf 'path = "%s/forktower.db"\n' "${DATA_DIR}"

    printf '\n[log]\n'
    printf 'level = "%s"\n' "${FORKTOWER_LOG_LEVEL:-info}"

    # Notification channels, if any were configured. The platform's own
    # notifications are the intended default and are not yet implemented, so a
    # deployment with nothing configured here will say plainly that it has no way
    # to reach its user — which is true, and better than silence.
    if [ -n "${FORKTOWER_WEBHOOK_URL:-}" ]; then
      printf '\n[[alerts.transport]]\n'
      printf 'name = "webhook"\ntype = "webhook"\nmin_tier = "%s"\n' \
        "${FORKTOWER_WEBHOOK_MIN_TIER:-warning}"
      printf 'url = "%s"\n' "${FORKTOWER_WEBHOOK_URL}"
    fi
    if [ -n "${FORKTOWER_NTFY_URL:-}" ]; then
      printf '\n[[alerts.transport]]\n'
      printf 'name = "ntfy"\ntype = "ntfy"\nmin_tier = "%s"\n' \
        "${FORKTOWER_NTFY_MIN_TIER:-warning}"
      printf 'url = "%s"\n' "${FORKTOWER_NTFY_URL}"
      [ -n "${FORKTOWER_NTFY_TOKEN:-}" ] && \
        printf 'token = "%s"\n' "${FORKTOWER_NTFY_TOKEN}"
    fi
  } > "${CONFIG}"

  # It holds credentials.
  chmod 600 "${CONFIG}"
  log "wrote ${CONFIG}"
}

# A password for the second node's RPC, generated once and kept. Nobody types it
# and nobody should have to: it authenticates one process to another inside the
# same container.
ensure_sq_password() {
  secret="${SQ_DIR}/rpc-password"
  if [ -z "${FORKTOWER_SQ_RPC_PASSWORD:-}" ]; then
    if [ ! -f "${secret}" ]; then
      head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n' > "${secret}"
      chmod 600 "${secret}"
    fi
    FORKTOWER_SQ_RPC_PASSWORD="$(cat "${secret}")"
    export FORKTOWER_SQ_RPC_PASSWORD
  fi
}

ensure_sq_password
if [ "${SQ_MODE}" = "all-in-one" ]; then
  write_bitcoin_conf
fi
write_forktower_conf

chown -R forktower:forktower "${DATA_DIR}" 2>/dev/null || true

log "Forktower starting (platform ${FORKTOWER_PLATFORM:-unspecified}, ${SQ_MODE})"

case "${SQ_MODE}" in
  all-in-one)
    # s6 supervises both processes. It is PID 1 from here.
    exec /init
    ;;
  external)
    # The second node is somebody else's service, so there is nothing to
    # supervise and the daemon can be PID 1 itself — which means it receives the
    # stop signal directly rather than through a layer that might not pass it on.
    #
    # By its full path: s6's tools are only on PATH once s6 is running, and here
    # it is not. Nothing in this container needs root, and a process holding
    # privileges it does not use is a process whose bugs are worth more to
    # somebody.
    exec /command/s6-setuidgid forktower /usr/local/bin/forktowerd --config "${CONFIG}"
    ;;
esac
