#!/usr/bin/env bash
#
# What is inside a Forktower release.
#
# Written by hand rather than generated by a scanner, because the interesting
# half of this software is not its Go modules. It is the three binaries fetched
# during the image build — Bitcoin Core, s6-overlay and yq — which no Go-aware
# tool would notice, and which are the parts that would matter most if one were
# found to be backdoored.
#
# Every one of them is pinned to a version and verified against a checksum
# committed in this repository, rather than one fetched alongside the download.
# A checksum an attacker can replace along with the file is not a check, and that
# distinction is the reason this list is worth reading.

set -euo pipefail

cd "$(dirname "$0")/.."

out="${1:-}"
[ -n "${out}" ] || { printf '  usage: make-sbom.sh <output-file>\n' >&2; exit 1; }

version="$(yq e '.version' manifest.yaml)"

# Read the pins out of the Dockerfile rather than restating them here: a bill of
# materials that can drift from what was built is worse than none, because it
# will be believed.
pin() { grep -m1 "^ARG ${1}=" Dockerfile | cut -d= -f2-; }

{
  printf '# Forktower %s — what is in it\n\n' "${version}"
  printf 'Generated by scripts/make-sbom.sh. The pinned versions and checksums\n'
  printf 'below are read from the Dockerfile, so this cannot drift from what was\n'
  printf 'actually built.\n\n'

  printf '## Bundled third-party binaries\n\n'
  printf 'Fetched during the image build and verified against checksums committed\n'
  printf 'in this repository — never against a checksum fetched beside the file.\n\n'
  printf '| Component | Version | Source | Checksum (x86_64) | Checksum (aarch64) |\n'
  printf '|---|---|---|---|---|\n'
  printf '| Bitcoin Core | %s | bitcoincore.org | `%s` | `%s` |\n' \
    "$(pin BITCOIN_VERSION)" "$(pin BITCOIN_SHA256_X86_64)" "$(pin BITCOIN_SHA256_AARCH64)"
  printf '| s6-overlay | %s | github.com/just-containers | `%s` | `%s` |\n' \
    "$(pin S6_OVERLAY_VERSION)" "$(pin S6_SHA256_X86_64)" "$(pin S6_SHA256_AARCH64)"
  printf '| yq | %s | github.com/mikefarah | `%s` | `%s` |\n' \
    "$(pin YQ_VERSION)" "$(pin YQ_SHA256_X86_64)" "$(pin YQ_SHA256_AARCH64)"
  printf '\n'

  printf 'Bitcoin Core is the second node, and its choice is a consensus decision\n'
  printf 'rather than a packaging one: Core has never merged BIP-110, so it follows\n'
  printf 'the chain this node exists to watch. `make check` asserts that of the\n'
  printf 'pinned binary rather than trusting the version number.\n\n'

  printf '## Base image\n\n'
  printf 'debian:bookworm-slim, plus `ca-certificates curl xz-utils tor jq` from\n'
  printf 'the Debian archives.\n\n'

  printf '## Go modules\n\n'
  printf 'The daemon is statically linked with cgo disabled. Direct dependencies:\n\n'
  printf '```\n'
  go list -m -f '{{if not .Indirect}}{{.Path}} {{.Version}}{{end}}' all 2>/dev/null \
    | grep -v '^$' | grep -v "^$(go list -m 2>/dev/null) " || true
  printf '```\n\n'
  printf 'The full module graph, including indirect dependencies and their\n'
  printf 'checksums, is `go.mod` and `go.sum` in this repository.\n\n'

  printf '## StartOS 0.4.x packaging\n\n'
  printf 'The package wrapper is TypeScript compiled to one file. Its only runtime\n'
  printf 'dependency is the platform SDK:\n\n'
  printf '```\n'
  grep -A 3 '"dependencies"' package.json | grep '":' | sed 's/[",]//g' | sed 's/^ *//' || true
  printf '```\n\n'
  printf 'None of it ships inside the container: it runs on the host as the\n'
  printf 'package supervisor.\n\n'

  printf '## What is deliberately not here\n\n'
  printf 'No telemetry, no analytics, no update check, and no code path that\n'
  printf 'fetches configuration. Forktower talks to the two Bitcoin nodes, the\n'
  printf 'Lightning node if one is configured, and whatever notification\n'
  printf 'transports the operator set up. Nothing else.\n'
} > "${out}"

printf '  wrote %s\n' "${out}"
